# Site settings
title: Jón Ingi Sveinbjörnsson
email: joningis@gmail.com
description: "Personal web page and programming blog of Jón Ingi Sveinbjörnsson."
baseurl: ""
url: "http://www.joningi.net"
github_username:  joningis
facebook_username: joningis
linkedin_userid: 24807790
linkedin_name: "Jón Ingi"

# Build settings
markdown: kramdown
permalink: pretty

defaults:
permalink: /:year/:month/:day/:title/

gems:
  - jekyll-sitemap
